spring:
  application:
    name: authentication-api

  datasource:
    url: jdbc:postgresql://localhost:5432/users-data
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: ZWxhdXRlLXNoZWlsYS1wb3ItdGVzdGUtYXV0aC1hcGk=
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs