services:

  postgres:
    container_name: authetication_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data: